"""HP BIOS configuration editor.

Supports two editing surfaces:

1. **REPSET (text) format** — HP BIOS Configuration Utility (``.REPSET``)
   files are plain-text files that list every BIOS setting and its allowed
   values.  This module can parse, modify, and re-serialise them.

2. **Binary patching** — direct byte-level patches on a raw BIOS ``.bin``
   file (e.g. changing a single byte at a known offset).

Typical usage::

    from hp_bios_tool.editor import BIOSConfigEditor

    editor = BIOSConfigEditor.from_file("current.REPSET")
    editor.set("USB Legacy Support", "Disabled")
    editor.set("Virtualization Technology (VTx)", "Enabled")
    editor.save("modified.REPSET")
"""

from __future__ import annotations

import io
import logging
import re
import struct
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .utils import hex_dump, safe_write

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# REPSET parser
# ---------------------------------------------------------------------------

# REPSET file looks like:
#
#   BIOSConfig 1.0
#   ;     HP BIOS Configuration - generated by BCU
#   ;
#   USB Legacy Support
#     *Enabled
#     Disabled
#   Virtualization Technology (VTx)
#     *Enabled
#     Disabled
#
# Lines starting with ";" are comments.
# A setting name is a line with no leading whitespace (and is not a comment
# or the header).
# Option values are indented; the selected value is prefixed with "*".

_HEADER_RE = re.compile(r"^BIOSConfig\s+\S+", re.IGNORECASE)


@dataclass
class BIOSSetting:
    """A single BIOS configuration entry.

    Attributes:
        name: Setting name exactly as it appears in the REPSET file.
        selected: Currently selected value.
        options: All allowed values for this setting.
        read_only: Whether the setting was marked read-only (``; Read Only``).
        comments: Any comment lines that immediately precede this setting.
    """

    name: str
    selected: str
    options: list[str] = field(default_factory=list)
    read_only: bool = False
    comments: list[str] = field(default_factory=list)

    def __repr__(self) -> str:
        return f"BIOSSetting(name={self.name!r}, selected={self.selected!r})"


class BIOSConfigEditor:
    """Parse, inspect, and modify HP BIOS REPSET configuration files.

    Args:
        settings: Ordered list of :class:`BIOSSetting` objects.
        header_comment: Header lines (comments) at the top of the file.
        version: REPSET version string (default ``"1.0"``).
    """

    def __init__(
        self,
        settings: Optional[list[BIOSSetting]] = None,
        header_comment: Optional[list[str]] = None,
        version: str = "1.0",
    ) -> None:
        self._settings: list[BIOSSetting] = settings or []
        self._index: dict[str, BIOSSetting] = {s.name: s for s in self._settings}
        self.header_comment: list[str] = header_comment or []
        self.version = version

    # ------------------------------------------------------------------
    # Constructors
    # ------------------------------------------------------------------

    @classmethod
    def from_file(cls, path: str | Path) -> "BIOSConfigEditor":
        """Load a REPSET file.

        Args:
            path: Path to the ``.REPSET`` file.

        Returns:
            :class:`BIOSConfigEditor` populated with the file's settings.
        """
        return cls.from_text(Path(path).read_text(encoding="utf-8", errors="replace"))

    @classmethod
    def from_text(cls, text: str) -> "BIOSConfigEditor":
        """Parse REPSET-formatted *text*.

        Args:
            text: Raw text content of a REPSET file.

        Returns:
            :class:`BIOSConfigEditor` instance.
        """
        lines = text.splitlines()
        header_comments: list[str] = []
        version = "1.0"
        settings: list[BIOSSetting] = []

        i = 0
        # Parse the header line
        while i < len(lines):
            line = lines[i]
            m = _HEADER_RE.match(line)
            if m:
                parts = line.split()
                if len(parts) >= 2:
                    version = parts[1]
                i += 1
                break
            if line.startswith(";"):
                header_comments.append(line)
            i += 1

        # Parse settings.
        # in_header_section: True until the first setting name is seen; during
        # this phase any comment lines are treated as header comments rather
        # than per-setting comments.
        in_header_section = True
        current_comments: list[str] = []
        current_name: Optional[str] = None
        current_options: list[str] = []
        current_selected: str = ""
        current_readonly: bool = False
        # A "; Read Only" comment can appear immediately before a setting name;
        # we track it here so the next setting picks it up.
        pending_readonly: bool = False

        def _flush() -> None:
            nonlocal current_name, current_options, current_selected
            nonlocal current_comments, current_readonly, pending_readonly
            if current_name is not None:
                settings.append(BIOSSetting(
                    name=current_name,
                    selected=current_selected,
                    options=list(current_options),
                    read_only=current_readonly,
                    comments=list(current_comments),
                ))
            current_name = None
            current_options = []
            current_selected = ""
            current_readonly = False
            current_comments = []

        while i < len(lines):
            line = lines[i]
            i += 1

            if not line.strip():
                continue

            # Comment line
            if line.startswith(";"):
                if current_name is not None:
                    # Comments inside a setting's option block
                    if "read only" in line.lower() or "readonly" in line.lower():
                        current_readonly = True
                elif in_header_section:
                    # Comments immediately after the BIOSConfig header line
                    header_comments.append(line)
                else:
                    # Between settings: check for read-only marker or accumulate
                    if "read only" in line.lower() or "readonly" in line.lower():
                        pending_readonly = True
                    else:
                        current_comments.append(line)
                continue

            # Indented line → option value for the current setting
            if line.startswith(("\t", "  ")):
                stripped = line.strip()
                if stripped.startswith("*"):
                    value = stripped[1:].strip()
                    current_selected = value
                    current_options.append(value)
                else:
                    current_options.append(stripped)
                continue

            # Non-indented, non-comment → new setting name
            in_header_section = False
            _flush()
            current_name = line.strip()
            current_readonly = pending_readonly
            pending_readonly = False

        _flush()  # flush the last setting

        return cls(settings, header_comments, version)

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def get(self, name: str) -> Optional[BIOSSetting]:
        """Return the :class:`BIOSSetting` with the given *name*, or *None*.

        Args:
            name: Exact setting name.
        """
        return self._index.get(name)

    def list_settings(self) -> list[BIOSSetting]:
        """Return all settings in file order."""
        return list(self._settings)

    def find(self, pattern: str, *, case_sensitive: bool = False) -> list[BIOSSetting]:
        """Return settings whose names match the regex *pattern*.

        Args:
            pattern: Regular expression to match against setting names.
            case_sensitive: Whether the match is case-sensitive.

        Returns:
            List of matching :class:`BIOSSetting` objects.
        """
        flags = 0 if case_sensitive else re.IGNORECASE
        rx = re.compile(pattern, flags)
        return [s for s in self._settings if rx.search(s.name)]

    # ------------------------------------------------------------------
    # Modify
    # ------------------------------------------------------------------

    def set(self, name: str, value: str) -> None:
        """Change the selected value of *name* to *value*.

        Args:
            name: Exact setting name.
            value: New value.  Must be one of the setting's allowed options.

        Raises:
            KeyError: If *name* does not exist in the config.
            ValueError: If *value* is not an allowed option for the setting.
        """
        setting = self._index.get(name)
        if setting is None:
            raise KeyError(f"Setting not found: {name!r}")
        if setting.options and value not in setting.options:
            raise ValueError(
                f"Invalid value {value!r} for {name!r}. "
                f"Allowed: {setting.options}"
            )
        if setting.read_only:
            logger.warning("Setting %r is marked read-only — writing anyway.", name)
        setting.selected = value
        logger.info("Set %r = %r", name, value)

    def set_many(self, changes: dict[str, str]) -> None:
        """Apply multiple setting changes at once.

        Args:
            changes: Mapping of ``{setting_name: new_value}``.
        """
        for name, value in changes.items():
            self.set(name, value)

    def add_setting(self, setting: BIOSSetting) -> None:
        """Append a new :class:`BIOSSetting` (e.g. for custom/unlocked settings).

        If a setting with the same name already exists it is replaced.

        Args:
            setting: Setting to add or replace.
        """
        if setting.name in self._index:
            old = self._index[setting.name]
            self._settings[self._settings.index(old)] = setting
        else:
            self._settings.append(setting)
        self._index[setting.name] = setting

    # ------------------------------------------------------------------
    # Serialise
    # ------------------------------------------------------------------

    def to_text(self) -> str:
        """Serialise settings back to REPSET format.

        Returns:
            REPSET-formatted string ready to write to a ``.REPSET`` file.
        """
        lines: list[str] = []
        lines.append(f"BIOSConfig {self.version}")
        lines.extend(self.header_comment)
        lines.append("")

        for s in self._settings:
            for c in s.comments:
                lines.append(c)
            if s.read_only:
                lines.append("; Read Only")
            lines.append(s.name)
            for opt in s.options:
                prefix = "*" if opt == s.selected else " "
                lines.append(f"\t{prefix}{opt}")
            lines.append("")

        return "\n".join(lines)

    def save(self, path: str | Path) -> None:
        """Write the current config to *path* in REPSET format.

        Args:
            path: Destination file path (typically ``.REPSET`` extension).
        """
        text = self.to_text()
        safe_write(Path(path), text.encode("utf-8"))
        logger.info("Config saved to %s", path)

    # ------------------------------------------------------------------
    # Diff
    # ------------------------------------------------------------------

    def diff(self, other: "BIOSConfigEditor") -> list[str]:
        """Return a human-readable diff between this config and *other*.

        Args:
            other: Another :class:`BIOSConfigEditor` to compare against.

        Returns:
            List of strings, one per changed setting.
        """
        lines: list[str] = []
        all_names = {s.name for s in self._settings} | {s.name for s in other._settings}
        for name in sorted(all_names):
            a = self._index.get(name)
            b = other._index.get(name)
            if a is None:
                lines.append(f"+ {name} = {b.selected!r}  (new)")  # type: ignore[union-attr]
            elif b is None:
                lines.append(f"- {name} = {a.selected!r}  (removed)")
            elif a.selected != b.selected:
                lines.append(f"  {name}: {a.selected!r} → {b.selected!r}")
        return lines


# ---------------------------------------------------------------------------
# Binary (raw BIOS) patcher
# ---------------------------------------------------------------------------

@dataclass
class BinaryPatch:
    """A single byte-level patch to apply to a BIOS binary.

    Attributes:
        offset: Byte offset within the file.
        original: Expected bytes at *offset* (used for safety verification).
        replacement: Replacement bytes to write.
        description: Human-readable description of this patch.
    """

    offset: int
    original: bytes
    replacement: bytes
    description: str = ""

    def validate_size(self) -> None:
        """Raise :exc:`ValueError` if original and replacement differ in length."""
        if len(self.original) != len(self.replacement):
            raise ValueError(
                f"Patch at 0x{self.offset:X}: original length "
                f"({len(self.original)}) ≠ replacement length "
                f"({len(self.replacement)})"
            )


class BIOSBinaryEditor:
    """Apply byte-level patches to a raw BIOS binary file.

    Args:
        data: Raw BIOS bytes.
    """

    def __init__(self, data: bytes) -> None:
        self._data = bytearray(data)

    # ------------------------------------------------------------------
    # Constructors
    # ------------------------------------------------------------------

    @classmethod
    def from_file(cls, path: str | Path) -> "BIOSBinaryEditor":
        """Load a BIOS binary from disk.

        Args:
            path: Path to the binary file (``.bin``, ``.rom``, etc.).
        """
        return cls(Path(path).read_bytes())

    # ------------------------------------------------------------------
    # Info
    # ------------------------------------------------------------------

    @property
    def size(self) -> int:
        """Size of the BIOS image in bytes."""
        return len(self._data)

    def hexdump(self, offset: int, length: int = 256) -> str:
        """Return a hex dump of *length* bytes starting at *offset*.

        Args:
            offset: Start offset.
            length: Number of bytes to dump.
        """
        return hex_dump(bytes(self._data[offset : offset + length]), start_offset=offset)

    def search(self, pattern: bytes) -> list[int]:
        """Find all occurrences of *pattern* in the binary.

        Args:
            pattern: Byte string to search for.

        Returns:
            List of offsets where *pattern* was found.
        """
        results: list[int] = []
        start = 0
        while True:
            pos = self._data.find(pattern, start)
            if pos == -1:
                break
            results.append(pos)
            start = pos + 1
        return results

    # ------------------------------------------------------------------
    # Patching
    # ------------------------------------------------------------------

    def apply_patch(self, patch: BinaryPatch, *, strict: bool = True) -> None:
        """Apply a single :class:`BinaryPatch`.

        Args:
            patch: The patch to apply.
            strict: If *True* (default), raise :exc:`ValueError` when the bytes
                at *patch.offset* do not match *patch.original*.

        Raises:
            ValueError: On size mismatch or, in strict mode, on data mismatch.
            IndexError: If the patch offset is out of range.
        """
        patch.validate_size()
        end = patch.offset + len(patch.original)
        if end > len(self._data):
            raise IndexError(
                f"Patch at 0x{patch.offset:X} extends beyond image "
                f"(image size 0x{len(self._data):X})"
            )
        actual = bytes(self._data[patch.offset : end])
        if strict and actual != patch.original:
            raise ValueError(
                f"Patch '{patch.description}' at 0x{patch.offset:X}: "
                f"expected {patch.original.hex()} but found {actual.hex()}"
            )
        self._data[patch.offset : end] = patch.replacement
        logger.info(
            "Applied patch '%s' at 0x%X: %s → %s",
            patch.description,
            patch.offset,
            patch.original.hex(),
            patch.replacement.hex(),
        )

    def apply_patches(self, patches: list[BinaryPatch], *, strict: bool = True) -> None:
        """Apply a list of patches in order.

        Args:
            patches: Patches to apply.
            strict: Passed to :meth:`apply_patch`.
        """
        for patch in patches:
            self.apply_patch(patch, strict=strict)

    def write_bytes(self, offset: int, data: bytes) -> None:
        """Overwrite bytes at *offset* without a safety check.

        Args:
            offset: Destination offset.
            data: Bytes to write.
        """
        end = offset + len(data)
        if end > len(self._data):
            raise IndexError(f"Write extends beyond image at 0x{offset:X}")
        self._data[offset : end] = data

    # ------------------------------------------------------------------
    # I/O
    # ------------------------------------------------------------------

    def to_bytes(self) -> bytes:
        """Return the (potentially modified) BIOS image as bytes."""
        return bytes(self._data)

    def save(self, path: str | Path) -> None:
        """Write the BIOS image to *path*.

        Args:
            path: Destination file path.
        """
        safe_write(Path(path), self.to_bytes())
        logger.info("BIOS binary saved to %s (%d bytes)", path, len(self._data))
